### ISSUE TITLE
(BUG) Using the aio version, it still requesting the API server

### ISSUE THREAD

**Issue by edersong** [enchant97/note-mark#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is This A Security Issue?

- [X] This is not a security issue

### Describe The Problem

Using the aio version, it still requesting the API server
![2023-12-27 211137](https://github.com/enchant97/note-mark/assets/64137913/f6555362-ce58-4209-bf25-6130ae550eee)

### Expected Behavior

Not ask for a API address

### Steps To Reproduce

Update docker container to aio version and try to login

**Comment by enchant97** [comment]
Working fine on a fresh install on mine. Ensure your `CORS_ORIGINS` is set correctly. If you were previously logged in try clearing your browser cache or just enter the server url with `/api` added on the end.

**Comment by edersong** [comment]
Cleared the browser cache worked! 
Thanks!
