### ISSUE TITLE
Docker export volume

### ISSUE THREAD

**Issue by ctrlbrk42** [enchant97/note-mark#173]
What is the path to export the data? I want to be sure it's backed up nightly.

**Comment by enchant97** [comment]
In the Official Docker image `-backend` or `-aio` data defaults to be `/data`. As set per `DATA_PATH`.

- https://notemark.docs.enchantedcode.co.uk/docs/setup/configuration/
- https://notemark.docs.enchantedcode.co.uk/docs/setup/backup/
