### ISSUE TITLE
(feat) Fetch "my notebooks" from home page (or all public, or bookmarked?)

### ISSUE THREAD

**Issue by Roundaround** [enchant97/note-mark#174]
### Does it fit the projects scope?

- [X] This is relevant

### Why?

The home page doesn't provide a whole lot of value to single-user setups because of the big empty "NOTEBOOKS" column on the left. I can see in the code you're only ever filling that with notes if the username URL param is provided:

https://github.com/enchant97/note-mark/blob/7855b71aace0ee27f587256ca9e91f9964e4a391/frontend/src/App.tsx#L49C1-L49C1

### Solution?

Perhaps we can fill the notebooks column with some actual results while on the non-user-specific home page? There are a few options:
- If logged in, simply use the logged in user's name as a fallback for the URL param to supply list of "my notes"
- Show all public notes (this could get out of hand quickly)
- Show bookmarked notes (as mentioned in the roadmap)

In fact, even all three of these could potentially get surfaced as different options, i.e. by throwing in a dropdown/tabs/radio group to select which you want to display

### Alternatives?

Obviously the main alternative solution would be to just remove the list altogether to reduce confusion since it doesn't get used, but that seems like a bit of a waste!

**Comment by enchant97** [comment]
At some point the homepage will be redesigned, so the drawer will not be there; unless logged in.

**Comment by enchant97** [comment]
It's now redesigned, forgot to link issue to commit.
