### ISSUE TITLE
(feat) Clickable breadcrumbs

### ISSUE THREAD

**Issue by Roundaround** [enchant97/note-mark#175]
### Does it fit the projects scope?

- [X] This is relevant

### Why?

While I will say this isn't a big problem because the app isn't deeply nested, it also feels like a pretty easy fix.

Short of it is the breadcrumbs are not clickable links like I would intuitively think.

### Solution?

Just change the `<span>` tag in each of the breadcrumbs into an `<a>` tag

**Comment by enchant97** [comment]
Should be very easy. Since there is a breadcrumb component that is fed the correct data already.
