### ISSUE TITLE
(feat) Add documentation for using CLI in docker/k8s with Distroless tools

### ISSUE THREAD

**Issue by shadowbq** [enchant97/note-mark#180]
### Does it fit the projects scope?

- [X] This is relevant

### Why?

When you chose distro-less docker images `gcr.io/distroless/static-debian11`, please document how to use the CLI tools. There is no common way to access the shell via `exec -it <shell>`

### Solution?

Document that you will need to exec directly to the init commands such as: 
kubectl exec -it <pod> --namespace=<NS> -- /note-mark <subcommand> <flags>

```sh
kubectl exec -it notemark-675c5fb966-tfk8c --namespace=notes -- /note-mark user -h
```

**Comment by enchant97** [comment]
Good idea, the recent demo video I made does show how to do this: https://youtu.be/rwL99Ac5g98
