### ISSUE TITLE
(BUG) Can't create notebook when one does not already exist

### ISSUE THREAD

**Issue by MBeggiato** [enchant97/note-mark#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is This A Security Issue?

- [X] This is not a security issue

### Describe The Problem

I just installed it and the ui is missing almost all features. I don't have any buttons to create notes:
![image](https://github.com/enchant97/note-mark/assets/15524763/22757a06-6152-4807-b13d-2cf142b3440a)

### Expected Behavior

![image](https://github.com/enchant97/note-mark/assets/15524763/8d857e61-d03b-47bd-a70c-b07f6f09c38b)

### Steps To Reproduce

Build using the following docker compose:
`# file: docker-compose.yml
# built-for: 0.10.0
version: "3"

volumes:
  data:

services:
  note-mark:
    image: ghcr.io/enchant97/note-mark-aio:0.10
    restart: unless-stopped
    volumes:
      - data:/data
    environment:
      # !!! REPLACE These !!!
      JWT_SECRET: "***********"
      CORS_ORIGINS: "https://example.com:8000"
    ports:
      - 80:8000`

### Environment

Docker Engine Community V 24.0.6
Ubuntu 22.04.2 LTS

**Comment by enchant97** [comment]
Great catch! I am working on a fix right now. Instead of a greyed out 'My Notes' button there will instead be a 'New Book' button.

**Comment by enchant97** [comment]
The new version is building now. Will be published as `0.11.1`. https://github.com/enchant97/note-mark/actions/runs/7739500384
