### ISSUE TITLE
(BUG) Notebooks list doesn't complete loading process

### ISSUE THREAD

**Issue by barefootpookie8** [enchant97/note-mark#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is This A Security Issue?

- [X] This is not a security issue

### Describe The Problem

The notebooks column on the left never loads. It continues to show the loading expanding circle, animation. Books and notes work properly when creating them and accessing them on the main section of the screen 

### Expected Behavior

From the demo, and screenshots, I should see a tree view of the books and notes I am adding as I add them. They never actually load.

### Steps To Reproduce

1. Create a new book
2. Look for the book on the left column under "NOTEBOOKS"

### Environment

macOS 14.4
Firefox 124.0.1
Apple Mac Mini M2 Pro

Docker Compose File:
  `note-mark:`
    `container_name: note-mark`
    `image: ghcr.io/enchant97/note-mark-aio:0.12.0`
    `restart: unless-stopped`
    `volumes:`
       `- /opt/note-mark/data:/data`
    `environment:`
       `JWT_SECRET: "*SECRET*"`
       `CORS_ORIGINS: "http://localhost:8000"`
   `ports:`
       `- '8000:8000'`

### Extra Context

![notemark issue](https://github.com/enchant97/note-mark/assets/41610444/56a70dc4-dffb-4e1f-b4f0-904bc842f6e5)
![CleanShot 2024-03-27 at 12 52 25](https://github.com/enchant97/note-mark/assets/41610444/12901c85-3aed-4455-928d-e803eb1f8910)
![Books and Notes](https://github.com/enchant97/note-mark/assets/41610444/7ab1966c-b665-49a6-83ad-6d2054bc3c68)

**Comment by rolikeusch** [comment]
the same issue is on macOS safari browser. I see the following error:

<img width="965" alt="note-mark-safari" src="https://github.com/enchant97/note-mark/assets/3592156/b85d9652-9ec3-4b44-9577-833ace096c2a">

**Comment by enchant97** [comment]
Thanks for the report, will investigate today.

**Comment by enchant97** [comment]
fixed by cebd05a72dc3ec96cfdce16ff4b66d76ddef3c94
