### ISSUE TITLE
(Ability to remove a book?) <Cannot see any option to remove a created book via web UI?>

### ISSUE THREAD

**Issue by 360john360** [enchant97/note-mark#193]
### Does it fit the projects scope?

- [X] This is relevant

### Why?

I created two titles and I need to delete one - because the slug is different is showcases both of them.

### Solution?

Add an option to remove a book.

**Comment by enchant97** [comment]
Deletion of a book can be accessed via Notebook settings. A note can be deleted via Note Settings. See below picture.
![Screenshot 2024-04-01 at 11 47 23](https://github.com/enchant97/note-mark/assets/25802519/955944cc-4763-44f6-9be5-e0d2b6c3627a)
