### ISSUE TITLE
Web page not loading with Mull Android web browser

### ISSUE THREAD

**Issue by jellytail** [enchant97/note-mark#199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is This A Security Issue?

- [X] This is not a security issue

### Describe The Problem

Low priority.
When opening Notes-Mark on my docker install only on the app [Mull](https://f-droid.org/en/packages/us.spotco.fennec_dos/) on Android loading the page does not work. All I get is a white loading page with a spinning wheel.
Using a browser that isn't hardened works perfectly and as expected.

### Expected Behavior

Web page opens normally.

**Comment by enchant97** [comment]
See supported browser list: https://notemark.docs.enchantedcode.co.uk/docs/usage/app/

```
Safari >= 17
Chrome >= 124
Firefox >= 125
```
