### ISSUE TITLE
(BUG) Copy To Clipboard Does Not Work On All Browsers

### ISSUE THREAD

**Issue by Mowen-M** [enchant97/note-mark#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is This A Security Issue?

- [X] This is not a security issue

### Describe The Problem

When i am sharing my note and upload an image to note assets want to copy the link, it will return “type error” to me. I rebuild the container and refresh database it still comes. By the way, the image that I upload i can open in browser which means the link is OK.

### Expected Behavior

Fix it
![IMG_1194](https://github.com/user-attachments/assets/63c9b188-cef9-46c3-86dc-5de031b1fca4)
![IMG_1195](https://github.com/user-attachments/assets/7e89e908-f57a-4063-9831-ff9b4ae41a5c)
![IMG_1196](https://github.com/user-attachments/assets/4bec4ff3-ad88-4c78-92b1-2931d8297c87)

### Steps To Reproduce

1. Create a note folder (set it to public)and create a note
2. Click the copy link bottom or upload a image to this note and then click copy the image
3. It will 100% comes out “type error”

### Environment

Docker,  latest version.
Porxy the web,
Bind ip is 0.0.0.0

**Comment by Mowen-M** [comment]
I have no idea what it happened, and i can use it last night when i set up the project

**Comment by enchant97** [comment]
Not sure why that would happen, works fine on my instance. Only issue I can think of is if you are accessing it with http, as it must be run accessed via https. *This is due to the copy-to-clipboard browser feature requiring https.*

**Comment by Mowen-M** [comment]
> Not sure why that would happen, works fine on my instance. Only issue I can think of is if you are accessing it with http, as it must be run accessed via https. *This is due to the copy-to-clipboard browser feature requiring https.*

I tried, only phones and iPads web browser can't copy the link. PC is fine.

**Comment by enchant97** [comment]
Thanks, I can confirm that both iPhone and iPad devices do not seem to function with clipboard functionality. Will investigate further when I have time.
