### ISSUE TITLE
(feat) Vim editing support.

### ISSUE THREAD

**Issue by wuguishifu** [enchant97/note-mark#207]
### Does it fit the projects scope?

- [x] This is relevant

### Why?

While not a feature everyone would use, those that do use vim daily would definitely be grateful. Other note apps have vim support as well (Obsidian, for example), so I think it's a reasonable feature.

### Solution?

Ideally, there would be a toggle that lets the user switch from normal input to vim input in the editor.

### Alternatives?

Editing in vscode or obsidian and then copy-pasting the files over. The only issue is that obsidian's formatting for markdown is slightly different than standard.

### Extra Context

Implementation in PR #209

**Comment by enchant97** [comment]
This would be a nice feature. I actually use vim to code this project!

**Comment by wuguishifu** [comment]
I can work on a quick implementation pr later today/tomorrow! I just added vim support to my own CM-based project so I've mostly figured out how it works.
