### ISSUE TITLE
(BUG) <title>cannot copy note link

### ISSUE THREAD

**Issue by angelflames1337** [enchant97/note-mark#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is This A Security Issue?

- [X] This is not a security issue

### Describe The Problem

clicking Copy Page Link on any note give errors as below 

_'clipboard-write' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName._

### Expected Behavior

It should copy the note URL to clipboard

### Steps To Reproduce

1. Go to any note
2. Click on the ...
3. Select Copy Page Link

error popped up

### Environment

ubuntu 22.04
docker compose.yml as below

```
 services:
   note-mark:
     image: ghcr.io/enchant97/note-mark-aio:0.13.1

    restart: unless-stopped
    volumes:
      - /srv/notemark/data:/data
    environment:
      # !!! REPLACE These !!!
      JWT_SECRET: "xxxxx"
      CORS_ORIGINS: "https://xxx.com"
    ports:
      - 7070:8000


```

**Comment by enchant97** [comment]
This may be a duplicate of #206. Can you add what browser & device you are using.

**Comment by angelflames1337** [comment]
Happen on WIndows 11 Firefox browser. On trying on Edge, it works fine. Not sure if it still bugs on Note Mark on is there anything I should do on Firefox to prevent this?

**Comment by enchant97** [comment]
I can now confirm this is a duplicate of #206.
