### ISSUE TITLE
(feat) make the edit bar sticky 

### ISSUE THREAD

**Issue by wurst44** [enchant97/note-mark#212]
### Does it fit the projects scope?

- [X] This is relevant

### Why?

It would be really nice if the edit bar (markdown) does stick on top, so when you scroll down it does not disappear and you are always able to use the edit bar. 

### Solution?

Edit bar sticks on top.

**Comment by enchant97** [comment]
This is already implemented if you make the editor fullscreen.

**Comment by wurst44** [comment]
Why would you only provide that feature in fullscreen? I seems to be a must have in non-fullscreen.

In addition to that I am also talking about the bar with the "plain, edtit" button to be sticky:
![image](https://github.com/user-attachments/assets/660406fa-aa5b-4afe-9e82-a757bf9b2f1e)

Thanks

**Comment by enchant97** [comment]
I have no plans to make the note view switcher stick to the top. The editor toolbar will also remain only sticky when in fullscreen. This is to ensure that there is plenty of room on mobile devices.

**Comment by wurst44** [comment]
I am using this great tool on a daily basis on all my devices, desktop and mobile. Please make the bars sticky on desktop, non-fullscreen also or at least let the user decide and make optionally. This would enormously improve usability!
Thx
