### ISSUE TITLE
(feat) Syntax highlighting in fenced code blocks

### ISSUE THREAD

**Issue by enchant97** [enchant97/note-mark#213]
### Discussed in https://github.com/enchant97/note-mark/discussions/211

<div type='discussions-op-text'>

<sup>Originally posted by **GiFuJo** October  3, 2024</sup>
Hi there! I wondered if syntax highlighting in fenced code blocks would fit the projects scope. I'm using Note Mark among other things to collect some code snippets I frequently use and it would be great to have syntax highlighting for those.</div>

**Comment by SmartPhoneLover** [comment]
I agree with this new feature.
