### ISSUE TITLE
(feat) Schedule based automatic backups

### ISSUE THREAD

**Issue by CrazyVito11** [enchant97/note-mark#218]
### Does it fit the projects scope?

- [X] This is relevant

### Why?

Currently making a backup of your notes requires you to create your own cron job on the server, which can get a bit more complicated if you are running the application containerized. It also requires you to make a copy of the database, which as far as I know, needs to not be running in order to make the backup.

### Solution?

It would be really nice if you can configure the application to automatically make the backup for you in a way that is considered "best practice" for Note Mark. Potentially via environment variables or the UI.

And if it can also make these backups for you while the application is still running, could make it very easy for the user to have it export these backups to a specific directory, that is then automatically synced to an external drive. _(NAS for example)_

### Alternatives?

In case this is too complicated to implement, it could also be an acceptable solution to have something like a bash script or command that automatically makes the backup of the database and notes, and dumps the files in a designated directory.

And if that is still considered too complicated, then another solution would be to make the documentation a bit more detailed. Maybe a list of commands that the user should run?

This way you can make it easier for users to make backups of their notes.

### Extra Context

At the moment I'm trying to improve my self hosted server by having it copy backups to a off-site NAS drive, so having a native solution inside Note Mark that periodically makes the backups would make it really easy to just mount my NAS in a specific directory to have off-site backups.

**Comment by enchant97** [comment]
Hi there, thanks for interest in the project!

I don't plan on having Note Mark create backups on its own. You should ideally create backups using an external program of choice.

A simple backup could be accomplished by first shutting down the container then copying the data directory and the database file (or creating a dump if using PostgreSQL). You can also make a backup whilst Note Mark is running as long as there are no users currently using it. The backup section of the documentation provides what directories will need to be backed up.

You can also use the Note Mark cli to export all data into a format that can be read outside of the application.

I think providing commands on how to backup a server is out of scope of the documentation. As they will be better covered on the respective sites.
