### ISSUE TITLE
(feat) PDF and other exports. 

### ISSUE THREAD

**Issue by voronind-com** [enchant97/note-mark#87]
### Does it fit the projects scope?

- [X] This is relevant

### Why?

sometimes you need to share a note with other people, or easily print it. it is much more convenient to send a pdf file instead of a link, especially if instance is not publically available.

### Solution?

implement PDF export, possibly other formats like html. it is implemented well in Joplin desktop editor (so you could see an example). 

### Alternatives?

none, at lease from project description/roadmap.

**Comment by enchant97** [comment]
Good idea!
