### ISSUE TITLE
(BUG) Tasks list spacing

### ISSUE THREAD

**Issue by franciscocabral** [enchant97/note-mark#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is This A Security Issue?

- [X] This is not a security issue

### Describe The Problem

The spacing between itens list is too high

### Expected Behavior

The spacing should be lower

### Steps To Reproduce

1. Create a new note
2. Create a item list

### Environment

Server
os: Manjaro
install method: Docker

Client
os: MacOS 13.0
browser: Chrome Version 116.0.5845.140 (Official Build) (arm64)

## Spacing at the note-mark rendered tab
![image](https://github.com/enchant97/note-mark/assets/4059355/84bef653-259e-4de4-94e3-fe40f97a7c24)

----

## Markdown code to reproduce the list:

# 📋 Tasks

- [x] task 1
- [x] task 2
- [ ] task 3
- [ ] task 4

**Comment by enchant97** [comment]
Very strange... The UI library I am using must have changed something without saying.
