### ISSUE TITLE
(BUG) Unexpected error when Creating a new notebook with a repeated slug

### ISSUE THREAD

**Issue by franciscocabral** [enchant97/note-mark#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is This A Security Issue?

- [X] This is not a security issue

### Describe The Problem

When creating a notebook, if you already have a notebook with the same slang, the API gives a error 500

### Expected Behavior

Should create a new notebook, using the same slug but incremented in 1 at the end.

original slug: personal
new slug? personal-1

not doing that makes people need to remember every slug that already been used.

### Steps To Reproduce

1. Create a notebook with slug: "my-notebook"
2. Create a new notebook with the same slug

### Environment

Server
os: Manjaro
install method: Docker

Client
os: MacOS 13.0
browser: Chrome Version 116.0.5845.140 (Official Build) (arm64)

**Comment by enchant97** [comment]
This is something that will be addressed in a future update.
