### ISSUE TITLE
(feat) Option to change sort order for notebooks and notes

### ISSUE THREAD

**Issue by pawelmalak** [enchant97/note-mark#94]
### Does it fit the projects scope?

- [X] This is relevant

### Why?

It would be nice to be able to sort notebooks and notes in different ways, according to current needs. This feature would make it easier to browse/find what we're currently looking for. It seems that now everything is sorted by creation time desc.

### Solution?

Add sorting options to both, notebooks and notes, lists/containers.

Optionally, this feature could also be extended with an option to set default sorting option for the whole app. Let's say that default sort is `Z to A`. User can change sorting in the current session, but after reloading webpage, sorting will be back to the default `Z to A`.

Example sorting options from Obsidian:

![image](https://github.com/enchant97/note-mark/assets/24780509/952113fa-42a9-4a55-b6cf-cd7735386932)

### Extra Context

Very promising project. Lately, I've been looking for something similar to Obsidian but simplified and with Web UI so Note Mark fits perfectly.

Looking forward to further updates and upcoming features. Great job and good luck!

**Comment by pawelmalak** [comment]
Also to add on to that, names should be ordered naturally, instead of classical alphanumerical sort.

```js
const names = ["note100", "note1", "note22"]

names.sort()
// ["note1", "note100", "note22"]

names.sort((a, b) => a.localeCompare(b, 'en', { sensitivity: 'base', numeric: true }))
// ["note1", "note22", "note100"]
```

**Comment by enchant97** [comment]
@pawelmalak out of interest what does Obsidian do?
